# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
smr_demo_run <- function(perc, lib_path, device = "GPU", verbose = TRUE, benchmark = FALSE) {
    .Call('_viewmastR2_smr_demo_run', PACKAGE = 'viewmastR2', perc, lib_path, device, verbose, benchmark)
}

#' @export
smr <- function(train_feats, test_feats, train_targets, test_targets, num_classes, query, lambda = 1.0, learning_rate = 2.0, iterations = 1000L, batch_size = 100L, max_error = 0.5, verbose = FALSE, benchmark = FALSE, device = 0L) {
    .Call('_viewmastR2_smr', PACKAGE = 'viewmastR2', train_feats, test_feats, train_targets, test_targets, num_classes, query, lambda, learning_rate, iterations, batch_size, max_error, verbose, benchmark, device)
}

computeSparseRowVariances <- function(j, val, rm, n) {
    .Call('_viewmastR2_computeSparseRowVariances', PACKAGE = 'viewmastR2', j, val, rm, n)
}

#' @export
get_sigmoid <- function(input) {
    .Call('_viewmastR2_get_sigmoid', PACKAGE = 'viewmastR2', input)
}

#' @export
get_relu <- function(input) {
    .Call('_viewmastR2_get_relu', PACKAGE = 'viewmastR2', input)
}

#' @export
get_mnist <- function(lib_path, perc = 80L, verbose = TRUE) {
    .Call('_viewmastR2_get_mnist', PACKAGE = 'viewmastR2', lib_path, perc, verbose)
}

#' @export
test_backends <- function() {
    .Call('_viewmastR2_test_backends', PACKAGE = 'viewmastR2')
}

